name: Update Version File

on:
  workflow_dispatch:
    inputs:
      new_stable_version:
        description: Updated version number for release

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      
      - name: Push commit
        run: |
          sed -i 'c\${{ github.event.inputs.new_stable_version }}' 'Nanolight Assets/VERSION'
          
          git add 'Nanolight Assets/VERSION'
          git commit -S -m 'Version update to ${{ github.event.inputs.new_stable_version }}'
          git push
